services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mv
      MYSQL_USER: e3
      MYSQL_PASSWORD: e3
    ports:
      - "3306:3306"
    # Montamos únicamente tu script de inicialización
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db-setup-e3.sql:/docker-entrypoint-initdb.d/db-setup-e3.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/mv?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: e3
      SPRING_DATASOURCE_PASSWORD: e3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    depends_on:
      - spring-app
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 2s
      retries: 3

volumes:
  mysql_data:
    driver: local