DROP SCHEMA IF EXISTS mv;
DROP USER IF EXISTS 'e3'@'localhost';

CREATE SCHEMA mv;
CREATE USER IF NOT EXISTS 'e3'@'localhost' IDENTIFIED BY 'e3';

GRANT ALL ON mv.* TO 'e3'@'e3' WITH GRANT OPTION;
FLUSH PRIVILEGES;


USE mv;

SHOW TABLES;
SELECT * FROM users;
SELECT * FROM items;
SELECT * FROM loans;